### ISSUE TITLE
Add more information about Guild Integrations

### ISSUE THREAD

**Issue by wonderwomancode** [unlock-protocol/docs#102]
Currently, we only mention Guild when we talk about token Token-gating a Discord, which we had a blog post about. However, Guild.xyz can be used for many more things and we should be specific about how useful that is considering how many integrations they now have;

Discord: verification, role management and gating for channels and servers
Telegram: gated chats and voting
GitHub: access to private repositories
Google: gating Drive folders or native files such as Docs, Sheets, or Slides. Different roles can have different levels of permission to the same folder or file (view only / comment / edit).
POAP: setup within Guild and distribution via the Guild Discord bot with optional voice chat participation requirement and monetization
Anywhere with [the Guild SDK](https://we/ just came out with a major update, adding google, github and twitter integrations to guild https://twitter.com/guildxyz/status/1557403374416531466?s=20&t=8fXfDhRcyq24SSqGJ3oXwg): either to token gate parts of a website or application, or to mirror existing membership structures and bridge them to other platforms in the Guild ecosystem

**Comment by patrickworkman** [comment]
Discord, Telegram, Google, and Github are the platforms available today. Guild (they've rebranded from Guild.xyz to Guild) is exploring adding 30+ integrations we can add as they are launched.

**Comment by ChialiTsai** [comment]
what will be the final text added to the article?

**Comment by wonderwomancode** [comment]
Finished
