### ISSUE TITLE
Fix internal docs search

### ISSUE THREAD

**Issue by wonderwomancode** [unlock-protocol/docs#125]
https://docusaurus.io/docs/search
https://docsearch.algolia.com/apply/

**Comment by wonderwomancode** [comment]
Getting errors when trying to sign-up for DocSearch Algolia free account for open-source projects. Rather than pay for another option that's hosted I'm going to go ahead and implement with local search since our docs aren't very large, bonus it works in offline mode. 

@julien51 @searchableguy any reasons you can think of to choose a different path forward? For reference here are the currently available [plugins](https://docusaurus.io/community/resources#search).

**Comment by wonderwomancode** [comment]
> 

It's not working very well. For instance, if you search "unlock accounts" the page with the title "Unlock Accounts" doesn't show up, but it will show up if you type "accounts". The problem is more than one person has tried to go back and find that page and can't because they're searching for what they remember the title to be. One of many examples of unexpected results from the search I've had people complain about recently.

<img width="969" alt="Screen Shot 2022-08-23 at 6 24 45 PM" src="https://user-images.githubusercontent.com/18197239/186297200-17015b5f-7ed2-43d5-bb03-6c6ee5b02f97.png">
<img width="1025" alt="Screen Shot 2022-08-23 at 6 26 21 PM" src="https://user-images.githubusercontent.com/18197239/186297325-b186d063-2f0f-4337-a613-40ef37ba83aa.png">
.

**Comment by ccarfi** [comment]
heck, google search seems to have things indexed ok
[https://www.google.com/search?q=site%3Adocs.unlock-protocol.com+unlock+accounts](https://www.google.com/search?q=site%3Adocs.unlock-protocol.com+unlock+accounts)

wonder if there's anything there that's usable in a pinch.

**Comment by julien51** [comment]
I suspect this is a configuration error.... for example I think we should tell the search engine to treat the "unlock" keyword differently (maybe ignore it!).

**Comment by searchableguy** [comment]
This can be closed. I replaced the local index with algolia.
