### ISSUE TITLE
Update the OpenAPI manifest file

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/docs#131]
The locksmith OpenAPI manifest file misses lots of endpoints. We need to update it to include these endpoints.
However, before we do that we need to make sure it is used to generate docs.

Assigning to @searchableguy for the doc generation part and to @wonderwomancode for the completion part!

**Comment by searchableguy** [comment]
I think we can close.

I documented most of the public APIs, added a script to automate PRs, and opened a PR to update the docs below. 

https://github.com/unlock-protocol/docs/pull/161
