### ISSUE TITLE
Deploying Locks on behalf of Users 

### ISSUE THREAD

**Issue by wonderwomancode** [unlock-protocol/docs#143]
High-level overview first and then details on how to do this programmatically.

**Comment by julien51** [comment]
Locks are deployed through the Unlock contract which acts as a "factory" contract.
There are multiple functions that enable the creation of a lock:
* `createLock` that provides the simplest interface as it takes arguments for the duration of each NFT membership (key), the currency contract address, the price, the maximum number of keys, the name... etc. It creates locks that are using the _current_ version of the protocol. As such, when new versions are introduces, if the signature differs, implementations _might_ break.
* `createUpgradableLockAtVersion` on the other end takes a `blob` of packed arguments as well as a version. This means that even though is is significantly harder to use (compacting arguments is a lot less readable), it will _always_ work for your application, as long as you accept to deploy lock in a _older_ version which users will need to upgrade. This is what the Unlock dashboard so we know we're not breaking the app. We also end up updating our front-end to support deploying new version.
* `createUpgradableLock` is the worst of both world :D but kept for legacy reason: it deploys blobs, but the blobs have to be built for the latest version... which means that when the protocol upgrades, application that rely on this might break.

It should be noted that despite its name `createLock` does create upgradable locks. 

All locks are upgradable... but only by the lock manager and only for upgrades to versions that are supported by the protocol (ie. approved by the DAO). Lock managers can "renounce" their role, making a lock un-upgradable.

To call contract you can use libraries like ethers or web3js.

We also created UnlockJs which does include a way to create locks programmatically (that is what we use on the Unlock dashboard for example): the `walletService` has [`createLock`](https://github.com/unlock-protocol/unlock/blob/master/packages/unlock-js/src/walletService.ts#L102) which can be called with a lock object that needs to include the following: TBC

**Comment by julien51** [comment]
Finally it is also possible to use the [hardhat plugin](https://www.npmjs.com/package/@unlock-protocol/hardhat-plugin), but this should be considered as a scripting tool, not a library that can be integrated in applications. The plugin includes both tasks that can be added to your own hardhat script, or a cli.

cc @clemsos who can write a bit more about this.

**Comment by wonderwomancode** [comment]
Added the last section. This is ready for final review.

**Comment by polluterofminds** [comment]
> We also created UnlockJs which does include a way to create locks programmatically (that is what we use on the Unlock dashboard for example): the `walletService` has [`createLock`](https://github.com/unlock-protocol/unlock/blob/master/packages/unlock-js/src/walletService.ts#L102) which can be called with a lock object that needs to include the following: TBC

This is what I'm experimenting with but struggling with understanding what parameters to pass in for recurring subscriptions using ERC20 tokens as payment.

**Comment by julien51** [comment]
> This is what I'm experimenting with but struggling with understanding what parameters to pass in for recurring subscriptions using ERC20 tokens as payment.

YEah we need to improve the docs A LOT on that, maybe with code examples. cc @wonderwomancode 
You only have to pass the ERC20 contract address as `currencyContractAddress`.

**Comment by julien51** [comment]
@polluterofminds What library do you use Ethers or web3.js or... ?

**Comment by polluterofminds** [comment]
> @polluterofminds What library do you use Ethers or web3.js or... ?

Trying to use wagmi.sh, which looks like uses ethers under the hood.

**Comment by julien51** [comment]
ha! ok, thanks, I'll have a tutorial/script ready for ethers and I'll look at wagmi.sh too

**Comment by julien51** [comment]
@polluterofminds I will have a full example up very soon (still learning wagmi!)
But here is a a snippet that I think will help:


```js
  const { address: creator } = useAccount()

  const [calldata, setCalldata] = React.useState('')
  const [name, setName] = React.useState('My Membership')
  const [price, setPrice] = React.useState(1)
  const [duration, setDuration] = React.useState(1) // in days
  const [supply, setSupply] = React.useState(10000)
  const [currency, setCurrency] = React.useState('0x0000000000000000000000000000000000000000') // address of the ERC20. If 0x0, uses base currency


  React.useEffect(() => {
    const prepareCalldata = async () => {
      // TODO: fecth actual decimals from ERC20 contract!
      const decimals = 18

      setCalldata(lockInterface.encodeFunctionData(
        'initialize(address,uint256,address,uint256,uint256,string)',
        [
          creator,
          duration * 60 * 24, // duration is in days!
          currency,
          ethers.utils.parseUnits(price.toString(), decimals),
          supply,
          name,
        ]
      ))
    }
    prepareCalldata()
  }, [creator, duration, currency, price, supply, name])


  const { config } = usePrepareContractWrite({
    addressOrName: '0x627118a4fB747016911e5cDA82e2E77C531e8206',
    contractInterface: UnlockV11.abi,
    functionName: 'createUpgradeableLockAtVersion',
    args: [calldata, 11] // We currently deploy version 11
  })
  const { transaction, sendTransaction } = useSendTransaction(config)
```

**Comment by julien51** [comment]
As lock creation function needs to be passed a "blob" and the version (each version might have a different blob format)!
The current version is 11, but you could also create 10 or 9 if you wanted to... (not recommended though!) and the blob for v11 needs to include the creator address, the duration of each NFT in seconds  (set MAXUINT if you want unlimited), the currency contract (or 0x0 if using the base currency of the chain), the price, including decimals, the supply (set MAXUINT if you want unlimited) and the name!

Let me know if this is helpful?
