### ISSUE TITLE
Spelling Error in Guides - two 'cc's in Protocol 

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/docs#148]
https://unlock-protocol.com/guides/cal-com-with-unlock-protoccol/

**Comment by julien51** [comment]
cc @ccarfi

**Comment by ccarfi** [comment]
updated.

there was also a typo in the URL with the double-c.

fixed the URL and added a redirect.

**Comment by ccarfi** [comment]
<img width="711" alt="Screen Shot 2022-09-15 at 12 31 33 PM" src="https://user-images.githubusercontent.com/214760/190492993-739a333e-c745-44a1-830b-b545879cd197.png">
