### ISSUE TITLE
Corrupted pdf files for security audits

### ISSUE THREAD

**Issue by wonderwomancode** [unlock-protocol/docs#175]
https://media.discordapp.net/attachments/974763163214032968/1027647375768031364/Screenshot_104.png?width=1774&height=688

**Comment by julien51** [comment]
@wonderwomancode 
[akira.pdf](https://github.com/unlock-protocol/docs/files/9843295/akira.pdf)
[byterocket.pdf](https://github.com/unlock-protocol/docs/files/9843296/byterocket.pdf)
[code4rena.pdf](https://github.com/unlock-protocol/docs/files/9843306/code4rena.pdf)
