### ISSUE TITLE
Add subgraph service from Unlock.js 

### ISSUE THREAD

**Issue by wonderwomancode** [unlock-protocol/docs#190]
Basic example 

https://github.com/unlock-protocol/unlock/blob/master/packages/unlock-js/examples/subgraph.js 

Add to
https://docs.unlock-protocol.com/tools/unlock.js/

**Comment by julien51** [comment]
@wonderwomancode Please consider also adding it to https://github.com/unlock-protocol/examples if this is more than a snippet. Thanks!

**Comment by SolomonFoskaay** [comment]
Is this still open or resolved?

**Comment by wonderwomancode** [comment]
@SolomonFoskaay yes this would be a good one if you want to take it up

**Comment by wonderwomancode** [comment]
@SolomonFoskaay As suggested in Discord it would be appropriate to add it to the bottom of the existing examples on that page.

Title: "Using the SubgraphService to query locks"

 @julien51 note above is a reference to a separate repository where we keep code examples, just follow that link. If you'd like to add it there under the javascript folder. I would create a new subfolder unlockjs and you can call the file subgraph-service.
