### ISSUE TITLE
nounce vs. nonce

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/docs#194]
should these three references be `nonce` instead of `nounce` ?

<img width="771" alt="Screen Shot 2022-10-24 at 4 25 22 PM" src="https://user-images.githubusercontent.com/214760/197648719-fee26a87-a111-4645-a132-9b47c64f07e5.png">

from here: https://github.com/unlock-protocol/docs/search?q=nounce

**Comment by searchableguy** [comment]
Yes.

https://en.m.wikipedia.org/wiki/Cryptographic_nonce

**Comment by julien51** [comment]
@searchableguy Want to submit a fix please?
