### ISSUE TITLE
Unlock Smart Contracts Naviagation loops

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/docs#203]
The bottom nav on Unlock Smart Contracts, points to Unlock Smart Contracts (the same page).

https://docs.unlock-protocol.com/core-protocol/
![0CC0E09B-99E0-4E94-B8D9-AD4B18535F65](https://user-images.githubusercontent.com/32484647/198896143-a8130676-9eec-41b1-ba43-51e0cfd2dfd9.jpeg)

**Comment by wonderwomancode** [comment]
Closing as duplicate of #186
