### ISSUE TITLE
Code4rena audit link points to a blank PDF

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/docs#204]
The [Code4rena audit link](https://docs.unlock-protocol.com/assets/files/code4rena-95ed151c60e0aaa3af66e6922409ed74.pdf) on the [Audits](https://docs.unlock-protocol.com/core-protocol/audits/) page of our docs points to a blank PDF [here](https://docs.unlock-protocol.com/assets/files/code4rena-95ed151c60e0aaa3af66e6922409ed74.pdf). 

Link should point to Protocol's Code4rena audit results.

**Comment by julien51** [comment]
Closing as duplicate. https://github.com/unlock-protocol/docs/issues/175
