### ISSUE TITLE
Update hook section with latest API

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/docs#223]
We have new hooks + some of changed.

**Comment by SolomonFoskaay** [comment]
> We have new hooks + some of changed.

How can I have access to them (new hooks + some of changed) and where are they expected to  be fixed in the docs?

**Comment by wonderwomancode** [comment]
> > We have new hooks + some of changed.
> 
> How can I have access to them (new hooks + some of changed) and where are they expected to be fixed in the docs?

I already put up a pull request for this one but for future reference. So you know the hooks smart contract interfaces can be found here https://github.com/unlock-protocol/unlock/tree/master/smart-contracts/contracts/interfaces/hooks

**Comment by SolomonFoskaay** [comment]
> > > We have new hooks + some of changed.
> > 
> > 
> > How can I have access to them (new hooks + some of changed) and where are they expected to be fixed in the docs?
> 
> I already put up a pull request for this one but for future reference. So you know the hooks smart contract interfaces can be found here https://github.com/unlock-protocol/unlock/tree/master/smart-contracts/contracts/interfaces/hooks

Noted. Thanks!
