### ISSUE TITLE
set up showcase.unlock-protocol.com subdomain

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/docs#239]
please add a new subdomain for:

showcase.unlock-protocol.com

that we can map to the new showcase site

**Comment by julien51** [comment]
Sure thing! I need to know what I need to map it to :D Let's maybe do that synchronously tomorrow?

**Comment by ccarfi** [comment]
cool. can do sync tomorrow, or update it in flywheel. i've gotten it to the point where flywheel needs to talk w/ cloudflare
https://app.getflywheel.com/juliengenestoux/unlock-showcase/domains/showcase.unlock-protocol.com/configure-dns

**Comment by julien51** [comment]
<img width="1120" alt="Screen Shot 2022-11-18 at 3 14 37 PM" src="https://user-images.githubusercontent.com/17735/202794348-8c5fb040-c3cf-4c9d-b428-d962c8c544bc.png">

All set!
