### ISSUE TITLE
Add pointer to Docs on Guides mobile navigation

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/docs#246]
There isn't a link to Unlock’s Developer Documentation on Guides’ mobile navigation. We should add one. 

![FC50D15D-DBCE-4C7C-896E-8F28AB39A42C](https://user-images.githubusercontent.com/32484647/204526108-b6e21186-90cb-403a-9ffe-a627aef1b3ae.png)

**Comment by wonderwomancode** [comment]
@0xChiali @ccarfi @kalidiagne adding you on this since it should be fixed when we add the new UI into the Guides, but leaving it open until that is finished.

**Comment by kalidiagne** [comment]
> @0xChiali @ccarfi @kalidiagne adding you on this since it should be fixed when we add the new UI into the Guides, but leaving it open until that is finished.

Yes, the new component will fix this

**Comment by kalidiagne** [comment]
fixed by https://github.com/unlock-protocol/unlock/pull/10564
