### ISSUE TITLE
Update README with info on auto-generated sections

### ISSUE THREAD

**Issue by wonderwomancode** [unlock-protocol/docs#252]
Some sections are auto-generated from the Unlock Protocol main repository, and some are auto-generated by plugins, we should document all of them in the README to make it clearer for contributors.

**Comment by julien51** [comment]
Please make sure svreenshot on this page is up to date https://docs.unlock-protocol.com/tools/checkout/

**Comment by wonderwomancode** [comment]
> 

I believe this was an accidental comment on this ticket. Associated screenshots have been updated though, so I'm not opening a separate ticket for it.
