### ISSUE TITLE
infinite loop on next page in subgraph page

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/docs#271]
the "next" button at the bottom refers back to the current page 

https://docs.unlock-protocol.com/tools/subgraph/

<img width="1408" alt="Screen Shot 2022-12-16 at 10 34 11 AM" src="https://user-images.githubusercontent.com/214760/208165912-d2f6afa7-8471-4d05-90a6-5599e267b3a4.png">

**Comment by julien51** [comment]
I think this is now fixed https://docs.unlock-protocol.com/tools/subgraph/
