### ISSUE TITLE
remove outdated authentication strategy

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/docs#282]
for locksmith and add detaisl about new approach!

**Comment by julien51** [comment]
The new approach is documented there https://discord.com/channels/462280183425138719/835883531438653460/1063104267549950163

**Comment by julien51** [comment]
@searchableguy Do you think you could add a quick tutorial as well as part of this? This would complete https://github.com/unlock-protocol/docs/issues/256

**Comment by searchableguy** [comment]
Will do.
