### ISSUE TITLE
CSS adjustment

### ISSUE THREAD

**Issue by ChialiTsai** [unlock-protocol/docs#34]
- [ ] Code box style - the text are not readable, need to fix

**Comment by ChialiTsai** [comment]
<img width="593" alt="image" src="https://user-images.githubusercontent.com/16527634/172631782-654a196d-e595-4371-839c-0fadd8b34136.png">

<img width="596" alt="image" src="https://user-images.githubusercontent.com/16527634/172631833-d6962463-d415-4a97-ae3c-f70faee878a7.png">


I overwrite some css and it cause the text not readable anymore... XD

**Comment by ChialiTsai** [comment]
issue happen in css-update branch

**Comment by kalidiagne** [comment]
@ChialiTsai added fix here

https://github.com/unlock-protocol/docs/pull/32/files#diff-44813f307e729042af7e70beff6f32ea63a7941bc100043a49e84d229ea2570fR205-R210 

this is the final result 
<img width="700" alt="Screenshot 2022-06-08 at 16 32 04" src="https://user-images.githubusercontent.com/20865711/172653750-dadcbc73-d6b8-490e-966c-69f9ba41b938.png">

**Comment by ChialiTsai** [comment]
thank you so much!

**Comment by julien51** [comment]
Very cool!
