### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by ChialiTsai** [unlock-protocol/docs#38]

**Comment by ChialiTsai** [comment]
when using automation to generate a doc page, it automatically create different pages for version, 
probably this solution can solve that, https://docusaurus.io/docs/versioning

<img width="715" alt="image" src="https://user-images.githubusercontent.com/16527634/172750432-292d02ab-be3d-4e4b-bb16-28fa626591e3.png">

**Comment by julien51** [comment]
We have now fixed this!
