### ISSUE TITLE
code syntax highlighter for Solidity

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/docs#39]
In this screenshot https://github.com/unlock-protocol/docs/issues/38#issuecomment-1150598825 , it seems that the Solidity code is not highlighted on the docs. 

We need to see how to support it https://docusaurus.io/docs/markdown-features/code-blocks#syntax-highlighting

**Comment by wonderwomancode** [comment]
Implemented: https://github.com/unlock-protocol/docs/pull/70
