### ISSUE TITLE
Shipping Docusaurus!

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/docs#40]
Here is a list of things/tasks we need to work on in order to ship the new docs:

- [x]  Merge smart contract autogenrated docs (by @clemsos )
- [x] css adjustment (https://github.com/unlock-protocol/docs/issues/34 )
- [x] #48
- [x] #47
- [x] #42
- [x] #41
- [x] #45
- [x] Tag site for Google and make sure we are not losing any SEO juice (permanent redirects are [supported in Docusaurus](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects)): `GTM-PRCCFV9`

Later (post launch):
- [ ] #43
- [ ] #44

**Comment by julien51** [comment]
@ChialiTsai says:

> Does June / 16th sounds reasonable for a soft deadline for everyone? (release to production)

Yes! Let's *freeze* gitbook so no more new changes are happening there and we can start (re)importing all of the docs from there.

**Comment by julien51** [comment]
Let's make sure we add GTM tracking : `GTM-PRCCFV9`

**Comment by wonderwomancode** [comment]
Shipped!
