### ISSUE TITLE
Add explanation for different flows unlock provide

### ISSUE THREAD

**Issue by wonderwomancode** [unlock-protocol/docs#71]
We don't make it clear there are two different flows developers can integrate into their applications.

We should make it clear when they would use checkout or sign in with ethereum and for what reasons. We should also list benefits over alternative or rolling out their own.

**Comment by wonderwomancode** [comment]
Add this to Basics > New to Unlock and make it the landing page there. Remember to update the link from the "Getting Started" page.

**Comment by julien51** [comment]
That's a good point.
The paywall is a "front-end only" integration, so we should only send people to that one if they _only_ want to do front-end (but even then it is not the only approach).

So I think we should first point people to the generic "building token gating application" on which we explain the 3 steps:
* identify the user
* check if they have an active membership
* (option) allow to purchase

Then, we should say, for folks who only want to do front-end, the paywall application actually does these 3 steps pretty easily.

**Comment by wonderwomancode** [comment]
Implemented in the restructuring
